name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2 # --> To Setup the Server With Node Env
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn

      - name: Types check
        run: yarn build

      - name: Lint
        run: yarn lint

      - name: Format
        run: yarn format

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: Linter - Github Action
          commit_user_email: lint_bot@github.com
          commit_message: 'Linted Code Base'
          add: '*'
